package model.EO;

import java.math.BigDecimal;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 25 11:36:19 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmNGGradingHeadersEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GdId {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getGdId();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        SalesOrderNumber {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getSalesOrderNumber();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setSalesOrderNumber((String)value);
            }
        }
        ,
        ItemId {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getItemId();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        GdDate {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getGdDate();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setGdDate((Date)value);
            }
        }
        ,
        JobSearch {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getJobSearch();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setJobSearch((String)value);
            }
        }
        ,
        JobQuantity {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getJobQuantity();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setJobQuantity((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        StitchQuantity {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getStitchQuantity();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setStitchQuantity((Number)value);
            }
        }
        ,
        CustPoNumber {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getCustPoNumber();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setCustPoNumber((String)value);
            }
        }
        ,
        JobId {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getJobId();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setJobId((BigDecimal)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        VersionNumber {
            public Object get(PwcOdmNGGradingHeadersEOImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(PwcOdmNGGradingHeadersEOImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcOdmNGGradingHeadersEOImpl object);

        public abstract void put(PwcOdmNGGradingHeadersEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GDID = AttributesEnum.GdId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int GDDATE = AttributesEnum.GdDate.index();
    public static final int JOBSEARCH = AttributesEnum.JobSearch.index();
    public static final int JOBQUANTITY = AttributesEnum.JobQuantity.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int STITCHQUANTITY = AttributesEnum.StitchQuantity.index();
    public static final int CUSTPONUMBER = AttributesEnum.CustPoNumber.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmNGGradingHeadersEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.EO.PwcOdmNGGradingHeadersEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for GdId, using the alias name GdId.
     * @return the GdId
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdId.
     * @param value value to set the GdId
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for SalesOrderNumber, using the alias name SalesOrderNumber.
     * @return the SalesOrderNumber
     */
    public String getSalesOrderNumber() {
        return (String)getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesOrderNumber.
     * @param value value to set the SalesOrderNumber
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for GdDate, using the alias name GdDate.
     * @return the GdDate
     */
    public Date getGdDate() {
        return (Date)getAttributeInternal(GDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdDate.
     * @param value value to set the GdDate
     */
    public void setGdDate(Date value) {
        setAttributeInternal(GDDATE, value);
    }

    /**
     * Gets the attribute value for JobSearch, using the alias name JobSearch.
     * @return the JobSearch
     */
    public String getJobSearch() {
        return (String)getAttributeInternal(JOBSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobSearch.
     * @param value value to set the JobSearch
     */
    public void setJobSearch(String value) {
        setAttributeInternal(JOBSEARCH, value);
    }

    /**
     * Gets the attribute value for JobQuantity, using the alias name JobQuantity.
     * @return the JobQuantity
     */
    public Number getJobQuantity() {
        return (Number)getAttributeInternal(JOBQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobQuantity.
     * @param value value to set the JobQuantity
     */
    public void setJobQuantity(Number value) {
        setAttributeInternal(JOBQUANTITY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedLogin, using the alias name LastUpdatedLogin.
     * @return the LastUpdatedLogin
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedLogin.
     * @param value value to set the LastUpdatedLogin
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for StitchQuantity, using the alias name StitchQuantity.
     * @return the StitchQuantity
     */
    public Number getStitchQuantity() {
        return (Number)getAttributeInternal(STITCHQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchQuantity.
     * @param value value to set the StitchQuantity
     */
    public void setStitchQuantity(Number value) {
        setAttributeInternal(STITCHQUANTITY, value);
    }

    /**
     * Gets the attribute value for CustPoNumber, using the alias name CustPoNumber.
     * @return the CustPoNumber
     */
    public String getCustPoNumber() {
        return (String)getAttributeInternal(CUSTPONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPoNumber.
     * @param value value to set the CustPoNumber
     */
    public void setCustPoNumber(String value) {
        setAttributeInternal(CUSTPONUMBER, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public BigDecimal getJobId() {
        return (BigDecimal)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(BigDecimal value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for MfgOrgId, using the alias name MfgOrgId.
     * @return the MfgOrgId
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MfgOrgId.
     * @param value value to set the MfgOrgId
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param gdId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number gdId) {
        return new Key(new Object[]{gdId});
    }


}
