package model.EO;

import java.math.BigDecimal;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 25 11:37:34 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmNGGradingLinesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /*protected void doDML(int operation, TransactionEvent e) 
    {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("user_id");
        System.out.println("User "+user);
        String respId = (String)sessionScope.get("resp_id");
        System.out.println("Resp Id "+respId);
        String orgId = (String)sessionScope.get("mfg_org_id");
        System.out.println("Org ID " + orgId);
        if(DML_UPDATE == operation)
        {
            try 
            {
                setLastUpdatedDate(new Timestamp(System.currentTimeMillis()));
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } 
            catch (SQLException f) 
            {
                System.out.println(f.getMessage());
            }
        } 
        if (DML_INSERT == operation)
        {
            try 
            {
                setCreationDate(new Timestamp(System.currentTimeMillis()));
                setCreatedBy(new oracle.jbo.domain.Number(user)); //RespId 
            } 
            catch (SQLException f) {;} 
            }
        super.doDML(operation, e);
    }*/
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StitchingLineId {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getStitchingLineId();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setStitchingLineId((Number)value);
            }
        }
        ,
        StitchingLineNo {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getStitchingLineNo();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setStitchingLineNo((String)value);
            }
        }
        ,
        GdId {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getGdId();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        TotalQuantity {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getTotalQuantity();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setTotalQuantity((Number)value);
            }
        }
        ,
        Gradea {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getGradea();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setGradea((Number)value);
            }
        }
        ,
        Gradeb {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getGradeb();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setGradeb((Number)value);
            }
        }
        ,
        Gradec {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getGradec();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setGradec((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        StitchingLineNumber {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getStitchingLineNumber();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setStitchingLineNumber((String)value);
            }
        }
        ,
        RetrunFlag {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getRetrunFlag();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setRetrunFlag((String)value);
            }
        }
        ,
        Rewash {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getRewash();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setRewash((Number)value);
            }
        }
        ,
        RequestStatus {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setOrgId((BigDecimal)value);
            }
        }
        ,
        LineDate {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getLineDate();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setLineDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(PwcOdmNGGradingLinesEOImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(PwcOdmNGGradingLinesEOImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcOdmNGGradingLinesEOImpl object);

        public abstract void put(PwcOdmNGGradingLinesEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STITCHINGLINEID = AttributesEnum.StitchingLineId.index();
    public static final int STITCHINGLINENO = AttributesEnum.StitchingLineNo.index();
    public static final int GDID = AttributesEnum.GdId.index();
    public static final int TOTALQUANTITY = AttributesEnum.TotalQuantity.index();
    public static final int GRADEA = AttributesEnum.Gradea.index();
    public static final int GRADEB = AttributesEnum.Gradeb.index();
    public static final int GRADEC = AttributesEnum.Gradec.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int STITCHINGLINENUMBER = AttributesEnum.StitchingLineNumber.index();
    public static final int RETRUNFLAG = AttributesEnum.RetrunFlag.index();
    public static final int REWASH = AttributesEnum.Rewash.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LINEDATE = AttributesEnum.LineDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmNGGradingLinesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.EO.PwcOdmNGGradingLinesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for StitchingLineId, using the alias name StitchingLineId.
     * @return the StitchingLineId
     */
    public Number getStitchingLineId() {
        return (Number)getAttributeInternal(STITCHINGLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingLineId.
     * @param value value to set the StitchingLineId
     */
    public void setStitchingLineId(Number value) {
        setAttributeInternal(STITCHINGLINEID, value);
    }

    /**
     * Gets the attribute value for StitchingLineNo, using the alias name StitchingLineNo.
     * @return the StitchingLineNo
     */
    public String getStitchingLineNo() {
        return (String)getAttributeInternal(STITCHINGLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingLineNo.
     * @param value value to set the StitchingLineNo
     */
    public void setStitchingLineNo(String value) {
        setAttributeInternal(STITCHINGLINENO, value);
    }

    /**
     * Gets the attribute value for GdId, using the alias name GdId.
     * @return the GdId
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdId.
     * @param value value to set the GdId
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for TotalQuantity, using the alias name TotalQuantity.
     * @return the TotalQuantity
     */
    public Number getTotalQuantity() {
        return (Number)getAttributeInternal(TOTALQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalQuantity.
     * @param value value to set the TotalQuantity
     */
    public void setTotalQuantity(Number value) {
        setAttributeInternal(TOTALQUANTITY, value);
    }

    /**
     * Gets the attribute value for Gradea, using the alias name Gradea.
     * @return the Gradea
     */
    public Number getGradea() {
        return (Number)getAttributeInternal(GRADEA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gradea.
     * @param value value to set the Gradea
     */
    public void setGradea(Number value) {
        setAttributeInternal(GRADEA, value);
    }

    /**
     * Gets the attribute value for Gradeb, using the alias name Gradeb.
     * @return the Gradeb
     */
    public Number getGradeb() {
        return (Number)getAttributeInternal(GRADEB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gradeb.
     * @param value value to set the Gradeb
     */
    public void setGradeb(Number value) {
        setAttributeInternal(GRADEB, value);
    }

    /**
     * Gets the attribute value for Gradec, using the alias name Gradec.
     * @return the Gradec
     */
    public Number getGradec() {
        return (Number)getAttributeInternal(GRADEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gradec.
     * @param value value to set the Gradec
     */
    public void setGradec(Number value) {
        setAttributeInternal(GRADEC, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedLogin, using the alias name LastUpdatedLogin.
     * @return the LastUpdatedLogin
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedLogin.
     * @param value value to set the LastUpdatedLogin
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }


    /**
     * Gets the attribute value for StitchingLineNumber, using the alias name StitchingLineNumber.
     * @return the StitchingLineNumber
     */
    public String getStitchingLineNumber() {
        return (String)getAttributeInternal(STITCHINGLINENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingLineNumber.
     * @param value value to set the StitchingLineNumber
     */
    public void setStitchingLineNumber(String value) {
        setAttributeInternal(STITCHINGLINENUMBER, value);
    }

    /**
     * Gets the attribute value for RetrunFlag, using the alias name RetrunFlag.
     * @return the RetrunFlag
     */
    public String getRetrunFlag() {
        return (String)getAttributeInternal(RETRUNFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for RetrunFlag.
     * @param value value to set the RetrunFlag
     */
    public void setRetrunFlag(String value) {
        setAttributeInternal(RETRUNFLAG, value);
    }

    /**
     * Gets the attribute value for Rewash, using the alias name Rewash.
     * @return the Rewash
     */
    public Number getRewash() {
        return (Number)getAttributeInternal(REWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rewash.
     * @param value value to set the Rewash
     */
    public void setRewash(Number value) {
        setAttributeInternal(REWASH, value);
    }


    /**
     * Gets the attribute value for RequestStatus, using the alias name RequestStatus.
     * @return the RequestStatus
     */
    public String getRequestStatus() {
        return (String)getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestStatus.
     * @param value value to set the RequestStatus
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for MfgOrgId, using the alias name MfgOrgId.
     * @return the MfgOrgId
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MfgOrgId.
     * @param value value to set the MfgOrgId
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }


    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public BigDecimal getOrgId() {
        return (BigDecimal)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(BigDecimal value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LineDate, using the alias name LineDate.
     * @return the LineDate
     */
    public Date getLineDate() {
        return (Date)getAttributeInternal(LINEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineDate.
     * @param value value to set the LineDate
     */
    public void setLineDate(Date value) {
        setAttributeInternal(LINEDATE, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param stitchingLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number stitchingLineId) {
        return new Key(new Object[]{stitchingLineId});
    }


}
