package model.VO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 20 11:37:49 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GradingTerryLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GradingTerryLinesVOImpl() {
    }
    
    @Override
         public void insertRow(Row row) {
             //go to the end of Rowset if it has rows
             Row lastRow = this.last();
             if (lastRow !=null){
                  //insert new row at the end and make it current
                 int indx = this.getRangeIndexOf(lastRow)+1;
                 this.insertRowAtRangeIndex(indx,row);
                 this.setCurrentRow(row);
             }else { // empty Rowset
             super.insertRow(row);
             }
             }
}
