package model.VO;

import java.math.BigDecimal;

import model.EO.PwcOdmNGGradingHeadersEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 25 18:17:40 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GradingTerryHeadersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        CustPoNumber {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getCustPoNumber();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setCustPoNumber((String)value);
            }
        }
        ,
        GdDate {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getGdDate();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setGdDate((Date)value);
            }
        }
        ,
        GdId {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getGdId();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getItemCode();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        ItemId {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getJobId();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setJobId((BigDecimal)value);
            }
        }
        ,
        JobQuantity {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getJobQuantity();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setJobQuantity((Number)value);
            }
        }
        ,
        Job {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getJob();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setJob((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        SalesOrderNumber {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSalesOrderNumber();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSalesOrderNumber((String)value);
            }
        }
        ,
        StitchQuantity {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getStitchQuantity();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setStitchQuantity((Number)value);
            }
        }
        ,
        JobSearch1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getJobSearch1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setJobSearch1((String)value);
            }
        }
        ,
        SumTotalQuantity {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSumTotalQuantity();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSumTotalQuantity((String)value);
            }
        }
        ,
        SumGradeA {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSumGradeA();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSumGradeA((String)value);
            }
        }
        ,
        SumGradeB {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSumGradeB();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSumGradeB((String)value);
            }
        }
        ,
        SumGradec {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSumGradec();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSumGradec((String)value);
            }
        }
        ,
        SumRewash {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getSumRewash();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setSumRewash((String)value);
            }
        }
        ,
        GradingTerryLinesVO {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getGradingTerryLinesVO();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingCustPoNo1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingCustPoNo1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingJob1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingJob1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingSalesOrderNoVO1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingSalesOrderNoVO1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingJobSearch1 {
            public Object get(GradingTerryHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingJobSearch1();
            }

            public void put(GradingTerryHeadersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(GradingTerryHeadersVORowImpl object);

        public abstract void put(GradingTerryHeadersVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUSTPONUMBER = AttributesEnum.CustPoNumber.index();
    public static final int GDDATE = AttributesEnum.GdDate.index();
    public static final int GDID = AttributesEnum.GdId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOBQUANTITY = AttributesEnum.JobQuantity.index();
    public static final int JOB = AttributesEnum.Job.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int STITCHQUANTITY = AttributesEnum.StitchQuantity.index();
    public static final int JOBSEARCH1 = AttributesEnum.JobSearch1.index();
    public static final int SUMTOTALQUANTITY = AttributesEnum.SumTotalQuantity.index();
    public static final int SUMGRADEA = AttributesEnum.SumGradeA.index();
    public static final int SUMGRADEB = AttributesEnum.SumGradeB.index();
    public static final int SUMGRADEC = AttributesEnum.SumGradec.index();
    public static final int SUMREWASH = AttributesEnum.SumRewash.index();
    public static final int GRADINGTERRYLINESVO = AttributesEnum.GradingTerryLinesVO.index();
    public static final int PWCODMGRADINGCUSTPONO1 = AttributesEnum.PwcOdmGradingCustPoNo1.index();
    public static final int PWCODMGRADINGJOB1 = AttributesEnum.PwcOdmGradingJob1.index();
    public static final int PWCODMGRADINGSALESORDERNOVO1 = AttributesEnum.PwcOdmGradingSalesOrderNoVO1.index();
    public static final int PWCODMGRADINGJOBSEARCH1 = AttributesEnum.PwcOdmGradingJobSearch1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GradingTerryHeadersVORowImpl() {
    }

    /**
     * Gets PwcOdmNGGradingHeadersEO entity object.
     * @return the PwcOdmNGGradingHeadersEO
     */
    public PwcOdmNGGradingHeadersEOImpl getPwcOdmNGGradingHeadersEO() {
        return (PwcOdmNGGradingHeadersEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUST_PO_NUMBER using the alias name CustPoNumber.
     * @return the CUST_PO_NUMBER
     */
    public String getCustPoNumber() {
        return (String) getAttributeInternal(CUSTPONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_PO_NUMBER using the alias name CustPoNumber.
     * @param value value to set the CUST_PO_NUMBER
     */
    public void setCustPoNumber(String value) {
        setAttributeInternal(CUSTPONUMBER, value);
    }

    /**
     * Gets the attribute value for GD_DATE using the alias name GdDate.
     * @return the GD_DATE
     */
    public Date getGdDate() {
        return (Date)getAttributeInternal(GDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_DATE using the alias name GdDate.
     * @param value value to set the GD_DATE
     */
    public void setGdDate(Date value) {
        setAttributeInternal(GDDATE, value);
    }

    /**
     * Gets the attribute value for GD_ID using the alias name GdId.
     * @return the GD_ID
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_ID using the alias name GdId.
     * @param value value to set the GD_ID
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public BigDecimal getJobId() {
        return (BigDecimal) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(BigDecimal value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for JOB_QUANTITY using the alias name JobQuantity.
     * @return the JOB_QUANTITY
     */
    public Number getJobQuantity() {
        return (Number)getAttributeInternal(JOBQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_QUANTITY using the alias name JobQuantity.
     * @param value value to set the JOB_QUANTITY
     */
    public void setJobQuantity(Number value) {
        setAttributeInternal(JOBQUANTITY, value);
    }

    /**
     * Gets the attribute value for JOB using the alias name Job.
     * @return the JOB
     */
    public String getJob() {
        return (String) getAttributeInternal(JOB);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB using the alias name Job.
     * @param value value to set the JOB
     */
    public void setJob(String value) {
        setAttributeInternal(JOB, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @return the MFG_ORG_ID
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @param value value to set the MFG_ORG_ID
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public String getSalesOrderNumber() {
        return (String) getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for STITCH_QUANTITY using the alias name StitchQuantity.
     * @return the STITCH_QUANTITY
     */
    public Number getStitchQuantity() {
        return (Number)getAttributeInternal(STITCHQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCH_QUANTITY using the alias name StitchQuantity.
     * @param value value to set the STITCH_QUANTITY
     */
    public void setStitchQuantity(Number value) {
        setAttributeInternal(STITCHQUANTITY, value);
    }

    /**
     * Gets the attribute value for JOB using the alias name JobSearch1.
     * @return the JOB
     */
    public String getJobSearch1() {
        return (String) getAttributeInternal(JOBSEARCH1);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB using the alias name JobSearch1.
     * @param value value to set the JOB
     */
    public void setJobSearch1(String value) {
        setAttributeInternal(JOBSEARCH1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumTotalQuantity.
     * @return the SumTotalQuantity
     */
    public String getSumTotalQuantity() {
        return (String) getAttributeInternal(SUMTOTALQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumTotalQuantity.
     * @param value value to set the  SumTotalQuantity
     */
    public void setSumTotalQuantity(String value) {
        setAttributeInternal(SUMTOTALQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeA.
     * @return the SumGradeA
     */
    public String getSumGradeA() {
        return (String) getAttributeInternal(SUMGRADEA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeA.
     * @param value value to set the  SumGradeA
     */
    public void setSumGradeA(String value) {
        setAttributeInternal(SUMGRADEA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeB.
     * @return the SumGradeB
     */
    public String getSumGradeB() {
        return (String) getAttributeInternal(SUMGRADEB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeB.
     * @param value value to set the  SumGradeB
     */
    public void setSumGradeB(String value) {
        setAttributeInternal(SUMGRADEB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradec.
     * @return the SumGradec
     */
    public String getSumGradec() {
        return (String) getAttributeInternal(SUMGRADEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradec.
     * @param value value to set the  SumGradec
     */
    public void setSumGradec(String value) {
        setAttributeInternal(SUMGRADEC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumRewash.
     * @return the SumRewash
     */
    public String getSumRewash() {
        return (String) getAttributeInternal(SUMREWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumRewash.
     * @param value value to set the  SumRewash
     */
    public void setSumRewash(String value) {
        setAttributeInternal(SUMREWASH, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GradingTerryLinesVO.
     */
    public RowIterator getGradingTerryLinesVO() {
        return (RowIterator)getAttributeInternal(GRADINGTERRYLINESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingCustPoNo1.
     */
    public RowSet getPwcOdmGradingCustPoNo1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGCUSTPONO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingJob1.
     */
    public RowSet getPwcOdmGradingJob1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGJOB1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingSalesOrderNoVO1.
     */
    public RowSet getPwcOdmGradingSalesOrderNoVO1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGSALESORDERNOVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingJobSearch1.
     */
    public RowSet getPwcOdmGradingJobSearch1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGJOBSEARCH1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
