package model.VO;

import java.math.BigDecimal;

import java.sql.Date;

import model.EO.PwcOdmNGGradingLinesEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 20 11:37:49 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GradingTerryLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        GdId {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getGdId();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        Gradea {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getGradea();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setGradea((Number)value);
            }
        }
        ,
        Gradeb {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getGradeb();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setGradeb((Number)value);
            }
        }
        ,
        Gradec {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getGradec();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setGradec((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        MfgOrgId {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getMfgOrgId();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setMfgOrgId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        RequestStatus {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        RetrunFlag {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getRetrunFlag();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setRetrunFlag((String)value);
            }
        }
        ,
        Rewash {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getRewash();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setRewash((Number)value);
            }
        }
        ,
        StitchingLineId {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getStitchingLineId();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setStitchingLineId((Number)value);
            }
        }
        ,
        StitchingLineNo {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getStitchingLineNo();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setStitchingLineNo((String)value);
            }
        }
        ,
        StitchingLineNumber {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getStitchingLineNumber();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setStitchingLineNumber((String)value);
            }
        }
        ,
        TotalQuantity {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getTotalQuantity();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setTotalQuantity((Number)value);
            }
        }
        ,
        SelectedRow {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getSelectedRow();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setSelectedRow((Boolean)value);
            }
        }
        ,
        RowSelected {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getRowSelected();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setRowSelected((Boolean)value);
            }
        }
        ,
        TotalQuantityTransient {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getTotalQuantityTransient();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setTotalQuantityTransient((Number)value);
            }
        }
        ,
        LineDate {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getLineDate();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setLineDate((oracle.jbo.domain.Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setVersionNumber((BigDecimal)value);
            }
        }
        ,
        PwcOdmGradingStitchingLineId1 {
            public Object get(GradingTerryLinesVORowImpl obj) {
                return obj.getPwcOdmGradingStitchingLineId1();
            }

            public void put(GradingTerryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(GradingTerryLinesVORowImpl object);

        public abstract void put(GradingTerryLinesVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int GDID = AttributesEnum.GdId.index();
    public static final int GRADEA = AttributesEnum.Gradea.index();
    public static final int GRADEB = AttributesEnum.Gradeb.index();
    public static final int GRADEC = AttributesEnum.Gradec.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int MFGORGID = AttributesEnum.MfgOrgId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int RETRUNFLAG = AttributesEnum.RetrunFlag.index();
    public static final int REWASH = AttributesEnum.Rewash.index();
    public static final int STITCHINGLINEID = AttributesEnum.StitchingLineId.index();
    public static final int STITCHINGLINENO = AttributesEnum.StitchingLineNo.index();
    public static final int STITCHINGLINENUMBER = AttributesEnum.StitchingLineNumber.index();
    public static final int TOTALQUANTITY = AttributesEnum.TotalQuantity.index();
    public static final int SELECTEDROW = AttributesEnum.SelectedRow.index();
    public static final int ROWSELECTED = AttributesEnum.RowSelected.index();
    public static final int TOTALQUANTITYTRANSIENT = AttributesEnum.TotalQuantityTransient.index();
    public static final int LINEDATE = AttributesEnum.LineDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int PWCODMGRADINGSTITCHINGLINEID1 = AttributesEnum.PwcOdmGradingStitchingLineId1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GradingTerryLinesVORowImpl() {
    }

    /**
     * Gets PwcOdmNGGradingLinesEO entity object.
     * @return the PwcOdmNGGradingLinesEO
     */
    public PwcOdmNGGradingLinesEOImpl getPwcOdmNGGradingLinesEO() {
        return (PwcOdmNGGradingLinesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for GD_ID using the alias name GdId.
     * @return the GD_ID
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_ID using the alias name GdId.
     * @param value value to set the GD_ID
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for GRADEA using the alias name Gradea.
     * @return the GRADEA
     */
    public Number getGradea() {
        return (Number)getAttributeInternal(GRADEA);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEA using the alias name Gradea.
     * @param value value to set the GRADEA
     */
    public void setGradea(Number value) {
        setAttributeInternal(GRADEA, value);
    }

    /**
     * Gets the attribute value for GRADEB using the alias name Gradeb.
     * @return the GRADEB
     */
    public Number getGradeb() {
        return (Number)getAttributeInternal(GRADEB);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEB using the alias name Gradeb.
     * @param value value to set the GRADEB
     */
    public void setGradeb(Number value) {
        setAttributeInternal(GRADEB, value);
    }

    /**
     * Gets the attribute value for GRADEC using the alias name Gradec.
     * @return the GRADEC
     */
    public Number getGradec() {
        return (Number)getAttributeInternal(GRADEC);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEC using the alias name Gradec.
     * @param value value to set the GRADEC
     */
    public void setGradec(Number value) {
        setAttributeInternal(GRADEC, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @return the MFG_ORG_ID
     */
    public Number getMfgOrgId() {
        return (Number)getAttributeInternal(MFGORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for MFG_ORG_ID using the alias name MfgOrgId.
     * @param value value to set the MFG_ORG_ID
     */
    public void setMfgOrgId(Number value) {
        setAttributeInternal(MFGORGID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for RETRUN_FLAG using the alias name RetrunFlag.
     * @return the RETRUN_FLAG
     */
    public String getRetrunFlag() {
        return (String) getAttributeInternal(RETRUNFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for RETRUN_FLAG using the alias name RetrunFlag.
     * @param value value to set the RETRUN_FLAG
     */
    public void setRetrunFlag(String value) {
        setAttributeInternal(RETRUNFLAG, value);
    }

    /**
     * Gets the attribute value for REWASH using the alias name Rewash.
     * @return the REWASH
     */
    public Number getRewash() {
        return (Number)getAttributeInternal(REWASH);
    }

    /**
     * Sets <code>value</code> as attribute value for REWASH using the alias name Rewash.
     * @param value value to set the REWASH
     */
    public void setRewash(Number value) {
        setAttributeInternal(REWASH, value);
    }

    /**
     * Gets the attribute value for STITCHING_LINE_ID using the alias name StitchingLineId.
     * @return the STITCHING_LINE_ID
     */
    public Number getStitchingLineId() {
        return (Number)getAttributeInternal(STITCHINGLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_LINE_ID using the alias name StitchingLineId.
     * @param value value to set the STITCHING_LINE_ID
     */
    public void setStitchingLineId(Number value) {
        setAttributeInternal(STITCHINGLINEID, value);
    }

    /**
     * Gets the attribute value for STITCHING_LINE_NO using the alias name StitchingLineNo.
     * @return the STITCHING_LINE_NO
     */
    public String getStitchingLineNo() {
        return (String) getAttributeInternal(STITCHINGLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_LINE_NO using the alias name StitchingLineNo.
     * @param value value to set the STITCHING_LINE_NO
     */
    public void setStitchingLineNo(String value) {
        setAttributeInternal(STITCHINGLINENO, value);
    }

    /**
     * Gets the attribute value for STITCHING_LINE_NUMBER using the alias name StitchingLineNumber.
     * @return the STITCHING_LINE_NUMBER
     */
    public String getStitchingLineNumber() {
        return (String) getAttributeInternal(STITCHINGLINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_LINE_NUMBER using the alias name StitchingLineNumber.
     * @param value value to set the STITCHING_LINE_NUMBER
     */
    public void setStitchingLineNumber(String value) {
        setAttributeInternal(STITCHINGLINENUMBER, value);
    }

    /**
     * Gets the attribute value for TOTAL_QUANTITY using the alias name TotalQuantity.
     * @return the TOTAL_QUANTITY
     */
    public Number getTotalQuantity() {
        return (Number)getAttributeInternal(TOTALQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_QUANTITY using the alias name TotalQuantity.
     * @param value value to set the TOTAL_QUANTITY
     */
    public void setTotalQuantity(Number value) {
        setAttributeInternal(TOTALQUANTITY, value);        
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedRow.
     * @return the SelectedRow
     */
    public Boolean getSelectedRow() {
        return (Boolean) getAttributeInternal(SELECTEDROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedRow.
     * @param value value to set the  SelectedRow
     */
    public void setSelectedRow(Boolean value) {
        setAttributeInternal(SELECTEDROW, value);
    }


    /**
     * Gets the attribute value for the calculated attribute RowSelected.
     * @return the RowSelected
     */
    public Boolean getRowSelected() {
        return (Boolean) getAttributeInternal(ROWSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowSelected.
     * @param value value to set the  RowSelected
     */
    public void setRowSelected(Boolean value) {
        setAttributeInternal(ROWSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalQuantityTransient.
     * @return the TotalQuantityTransient
     */
    public Number getTotalQuantityTransient() {
        return (Number)getAttributeInternal(TOTALQUANTITYTRANSIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalQuantityTransient.
     * @param value value to set the  TotalQuantityTransient
     */
    public void setTotalQuantityTransient(Number value) {
        value = getGradea().add(getGradeb());
        value.add(getGradec());
        value.add(getRewash());
        setAttributeInternal(TOTALQUANTITYTRANSIENT, value);
        
    }

    /**
     * Gets the attribute value for LINE_DATE using the alias name LineDate.
     * @return the LINE_DATE
     */
    public oracle.jbo.domain.Date getLineDate() {
        return (oracle.jbo.domain.Date) getAttributeInternal(LINEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_DATE using the alias name LineDate.
     * @param value value to set the LINE_DATE
     */
    public void setLineDate(oracle.jbo.domain.Date value) {
        setAttributeInternal(LINEDATE, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingStitchingLineId1.
     */
    public RowSet getPwcOdmGradingStitchingLineId1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGSTITCHINGLINEID1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
