package model.AM.client;

import model.AM.common.PwcOdmGradingTerryAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 25 11:55:24 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingTerryAMClient extends ApplicationModuleImpl implements PwcOdmGradingTerryAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingTerryAMClient() {
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl, String mfgOrgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl, mfgOrgId});
        return;
    }

    public String callAPIProc(int sqlReturnType, String stmt,
                              String requestStatus) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callAPIProc",new String [] {"int","java.lang.String","java.lang.String"},new Object[] {new Integer(sqlReturnType), stmt, requestStatus});
        return (String)_ret;
    }
}
