package model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 25 11:55:24 PKT 2018
// ---------------------------------------------------------------------
public interface PwcOdmGradingTerryAM extends ApplicationModule {
    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl, String mfgOrgId);

    String callAPIProc(int sqlReturnType, String stmt, String requestStatus);
}
